# Generated by Django 3.0.7 on 2020-06-12 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0002_auto_20200612_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='references',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='references',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to=settings.AUTH_USER_MODEL),
        ),
    ]
